import { COMPANY_DETAILS, PACKAGE_TIERS, COMPENSATION_STREAMS, RANK_AWARDS } from './compensationData';
import { PRODUCTS } from './productsData';

export interface BotResponse {
  text: string;
  actionButton?: {
    label: string;
    path: string;
  };
  copyData?: {
    label: string;
    text: string;
  };
  relatedSuggestions?: string[];
}

export const BINARY_PAIRING_EXPLANATION: BotResponse = {
  text: `### ⚡ The 14% Binary Pairing Bonus (Explained in Detail)

The **14% Binary Pairing Bonus** is Milnapath’s most powerful fast-track residual income stream. It rewards you for building and balancing two sales teams: your **Left Leg** and your **Right Leg**.

---

#### 1. The Core Formula
* **1 Pair** = **40 PV** on your Left Leg matched with **40 PV** on your Right Leg.
* The company pays you **14%** of the matched PV volume:
  $$\\text{14\\% of 40 PV} = 5.6 \\text{ PV} = \\$5.60 \\text{ USD}$$
* At Milnapath’s official fixed exchange rate of **1 PV = $1.00 = ₦500**:
  $$\\mathbf{5.6 \\times ₦500 = ₦2,800 \\text{ Cash Per Pair!}}$$

---

#### 2. Earning Multiples at a Glance
* **1 Pair** (40 PV Left & Right) = **₦2,800**
* **5 Pairs** (200 PV Left & Right) = **₦14,000**
* **10 Pairs** (400 PV Left & Right) = **₦28,000**
* **25 Pairs** (Entry Tier Daily Cap) = **₦70,000 / day**
* **40 Pairs** (Standard Tier Daily Cap) = **₦112,000 / day**
* **60 Pairs** (Executive Tier Daily Cap) = **₦168,000 / day**
* **100 Pairs** (Elite Tier Daily Cap) = **₦280,000 / day**
* **175 Pairs** (VIP Tier Daily Cap) = **₦490,000 / day** ($$\\approx$$ **₦14,700,000 / month!**)

---

#### 3. Why Milnapath's Binary is Superior
1. **Uncapped Depth to Infinity**: It does not matter whether pairs are generated by your direct sign-ups, your downlines' downlines, or massive **spillover** from your upline mentor. As long as points balance on both legs, you are paid!
2. **Never-Flush Points Policy**: Unlike old network marketing companies that wipe out your hard work at month-end, Milnapath **NEVER flushes unmatched points**. Any extra PV on your stronger leg carries over indefinitely into the next day and month.
3. **Dual Advantage (Rank Qualification)**: Every single PV you generate in your lesser leg also counts toward your cumulative awards—advancing you toward the **Laptop**, **₦5M Brand New Car**, **₦15M SUV**, and **₦60M Luxury Villa**!`,
  actionButton: {
    label: 'Open Compensation Calculator',
    path: '/compensation'
  },
  relatedSuggestions: [
    'What are the package tiers and daily caps?',
    'How do I register with ₦10,000 Foretaste?',
    'Do points ever flush or expire?'
  ]
};

export const QUICK_PROMPTS = [
  'Explain the 14% binary pairing bonus',
  'How do I register with ₦10,000 (GT Bank)?',
  'What are the 12 Ways to Earn in Milnapath?',
  'Which product is best for ulcer & acid reflux?',
  'Tell me about Gynomil for fibroids & fertility',
  'Do points flush at the end of the month?',
  'What are the package tiers & daily binary caps?',
  'How much do Milnapath stockists earn?'
];

export function getBotAnswer(query: string): BotResponse {
  const q = query.toLowerCase().trim();

  // 1. Binary pairing bonus query (Explicit match)
  if (
    q.includes('14%') ||
    (q.includes('binary') && (q.includes('pairing') || q.includes('bonus') || q.includes('explain') || q.includes('work') || q.includes('14'))) ||
    q.includes('pairing bonus') ||
    q.includes('how does pairing work') ||
    q.includes('binary pairing')
  ) {
    return BINARY_PAIRING_EXPLANATION;
  }

  // 2. Registration & Bank Account Queries
  if (
    q.includes('register') ||
    q.includes('join') ||
    q.includes('gt bank') ||
    q.includes('account number') ||
    q.includes('10,000') ||
    q.includes('10000') ||
    q.includes('10k') ||
    q.includes('foretaste') ||
    q.includes('how to start') ||
    q.includes('sign up') ||
    q.includes('payment')
  ) {
    return {
      text: `### 📝 How to Register with Milnapath International (₦10,000 Foretaste)

Joining Milnapath takes less than 5 minutes through our official company gateway:

#### Official Company Bank Account:
* **Bank:** Guaranty Trust Bank (GTBank)
* **Account Name:** Millennium Nature's Path Intl
* **Account Number:** **0718549018**
* **Registration Cost:** **₦10,000** (Foretaste Tier)

#### What You Receive Immediately Upon Registration:
* **1 Bottle of Detox Plus** (valued at ₦13,500 retail)
* **10 Personal PV** assigned to your distributor ID
* Placement in the **3-Level Foretaste Referral Matrix** (Earn ₦2,000 Direct, ₦600 1st Indirect, ₦400 2nd Indirect)
* Access to the **VIP Direct Mentorship Mastermind** with free sales funnels, weekly live Zoom trainings, and automated team spillover!

#### 3 Simple Steps to Complete Your Registration:
1. Pay **₦10,000** directly to the GT Bank account above.
2. Click **Go to Registration Form** below.
3. Fill in your personal details, upload payment proof/reference, and select your preferred product delivery method or stockist pickup center.`,
      copyData: {
        label: 'GT Bank Account Number',
        text: '0718549018'
      },
      actionButton: {
        label: 'Go to Registration Form (₦10,000)',
        path: '/register'
      },
      relatedSuggestions: [
        'Explain the 14% binary pairing bonus',
        'Can I upgrade my package later?',
        'What are the 12 Ways to Earn?'
      ]
    };
  }

  // 3. The 12 Ways to Earn
  if (
    q.includes('12 ways') ||
    q.includes('earn') ||
    q.includes('compensation') ||
    q.includes('income stream') ||
    q.includes('how do i make money') ||
    q.includes('ways to make money') ||
    q.includes('comp plan')
  ) {
    return {
      text: `### 💰 The 12 Ways to Earn in Milnapath International

Milnapath has designed the most generous, never-flushing compensation plan in African direct sales:

1. **Foretaste 3-Level Referral Bonus:** 30% total payout on ₦10k sign-ups (20% direct = ₦2,000; 6% Gen 2 = ₦600; 4% Gen 3 = ₦400).
2. **Direct Activation Bonus:** 20% to 28% instant commission on business package purchases (up to ₦156,800 for direct VIP).
3. **Upgrade Bonus:** Earn full sponsor percentage whenever your downlines upgrade their package tiers.
4. **14% Binary Pairing Bonus:** Earn ₦2,800 per 40 PV pair matched to infinite depth, with daily caps up to ₦490,000/day.
5. **20% Repurchase Cashback:** Get 20% cashback directly to your e-wallet on all personal monthly re-orders.
6. **12-Level Unilevel Residual Bonus:** Earn compressed monthly percentages on team re-orders (Gen 1: 7%, Gen 2: 6%, Gen 3: 5%, down to 12 levels).
7. **25% Retail Profit Margin:** Buy at wholesale distributor price and sell to consumers at retail for instant pocket cash.
8. **Monthly Lifestyle Awards:** Cash stipends from ₦125,000 to ₦1,000,000 + all-expense paid 5-star international travel.
9. **Cumulative Rank Awards (Never Flushes):** Electronics (₦70k), Laptop (₦250k), Vacation (₦1M), 1st Car (₦5M), 2nd Luxury Car (₦15M), Prado SUV (₦30M), and a ₦60 Million Luxury Villa!
10. **Special Promo Awards:** Quarterly smartphone, cash, and hamper challenge pools.
11. **Stockist Hub Commissions:** Earn 4.5% to 7.5% profit override on all products distributed through your center.
12. **3% Global Profit Pool:** Top Diamond leaders share 3% of worldwide company quarterly PV.`,
      actionButton: {
        label: 'Explore Complete Compensation Guide',
        path: '/compensation'
      },
      relatedSuggestions: [
        'Explain the 14% binary pairing bonus',
        'Tell me about the Car & Villa Awards',
        'What are the package tiers?'
      ]
    };
  }

  // 4. Ulcer / Gastro-Pro / Peptic Tea Queries
  if (
    q.includes('ulcer') ||
    q.includes('gastro') ||
    q.includes('stomach') ||
    q.includes('gastritis') ||
    q.includes('acid reflux') ||
    q.includes('heartburn') ||
    q.includes('peptic') ||
    q.includes('pylori')
  ) {
    return {
      text: `### 🌿 Best Milnapath Products for Peptic Ulcers & Acid Reflux

For chronic peptic ulcers, gastritis, H. Pylori, and acid reflux, Milnapath provides a clinically proven botanical combination:

#### 1. Gastro-Pro (The Core Remedy)
* **Retail Price:** ₦12,000 | **Wholesale:** ₦9,500 (12 PV)
* **Actions:** Neutralizes gastric inflammation, destroys *Helicobacter pylori* bacteria, and stimulates rapid cellular rebuilding of damaged stomach mucosa.

#### 2. Peptic Tea (Gentle Daily Healing & Soothing)
* **Retail Price:** ₦8,500 | **Wholesale:** ₦6,500 (8 PV)
* **Actions:** Herbal infusion taken morning and night. Shields gastric tissue against hydrochloric acid, restores alkaline balance, and halts burning chest sensations.

*Tip:* Combining **Gastro-Pro** with **Peptic Tea** delivers complete eradication of chronic ulcer pain within 14 to 28 days.`,
      actionButton: {
        label: 'View Gastro-Pro Details',
        path: '/products/gastro-pro'
      },
      relatedSuggestions: [
        'Tell me about Detox Plus',
        'What are the 12 products?',
        'How do I order products?'
      ]
    };
  }

  // 5. Gynomil / Fibroids / Female Health Queries
  if (
    q.includes('gynomil') ||
    q.includes('fibroid') ||
    q.includes('cyst') ||
    q.includes('fertility') ||
    q.includes('infertility') ||
    q.includes('fallopian') ||
    q.includes('period') ||
    q.includes('menstrua') ||
    q.includes('hormon') ||
    q.includes('womb') ||
    q.includes('ovulation')
  ) {
    return {
      text: `### 🌸 Gynomil: The Female Botanical Restoration Miracle

**Gynomil** is Milnapath's premier herbal therapy for feminine reproductive health, hormonal alignment, and natural conception:

* **Retail Price:** ₦14,000 | **Wholesale Price:** ₦11,000 (15 PV)
* **NAFDAC Approved & 100% Herbal**

#### Primary Health Indications:
* **Uterine Fibroids & Ovarian Cysts:** Helps dissolve non-cancerous uterine growths and ovarian fluid sacs safely without invasive surgical procedures.
* **Blocked Fallopian Tubes:** Clears pelvic inflammation and assists in unblocking natural reproductive passageways.
* **Hormonal Imbalance & Irregular Menses:** Balances estrogen-progesterone ratios, stops heavy clotting, relieves severe menstrual cramps, and restores normal 28-day cycles.
* **Ovulation & Fertility Boost:** Enhances follicular egg quality and prepares the uterine endometrial wall for successful pregnancy implantation.`,
      actionButton: {
        label: 'Read Gynomil Full Clinical Profile',
        path: '/products/gynomil'
      },
      relatedSuggestions: [
        'Tell me about Detox Plus',
        'How to order Gynomil at wholesale',
        'What is the ₦10,000 registration?'
      ]
    };
  }

  // 6. Nakom Oil / Arthritis / Joint / Pain Queries
  if (
    q.includes('nakom') ||
    q.includes('arthritis') ||
    q.includes('joint') ||
    q.includes('rheumatism') ||
    q.includes('waist pain') ||
    q.includes('back pain') ||
    q.includes('stroke') ||
    q.includes('pain')
  ) {
    return {
      text: `### 💧 Nakom Oil: Deep-Penetrating Pain Relief & Mobility

**Nakom Oil** is a fast-acting, cold-pressed therapeutic herbal rub formulated for deep musculoskeletal relief:

* **Retail Price:** ₦11,500 | **Wholesale Price:** ₦9,000 (12 PV)
* **Indications:** Severe osteoarthritis, rheumatoid joint stiffness, lower waist ache, sciatica nerve pain, neck strain, and post-stroke motor rehabilitation.
* **Action:** Penetrates within minutes of topical massage to stimulate capillary blood circulation, soothe inflamed cartilage, and unlock frozen joints.`,
      actionButton: {
        label: 'View Nakom Oil Profile',
        path: '/products/nakom-oil'
      },
      relatedSuggestions: [
        'What are all 12 products?',
        'How to register with ₦10,000',
        'Explain the 14% binary pairing bonus'
      ]
    };
  }

  // 7. Detox Plus Queries
  if (
    q.includes('detox') ||
    q.includes('cleanse') ||
    q.includes('constipat') ||
    q.includes('toxin') ||
    q.includes('liver') ||
    q.includes('colon')
  ) {
    return {
      text: `### 🍃 Detox Plus: Complete Systemic Detoxification

**Detox Plus** is Milnapath’s flagship full-body cleanser and rejuvenation formula (included FREE in the ₦10,000 Foretaste registration package):

* **Retail Price:** ₦9,500 | **Wholesale Price:** ₦7,500 (10 PV)
* **Health Benefits:** Clears impacted fecal toxins from the colon, relieves chronic constipation, purifies the liver and blood, enhances nutrient absorption, and revitalizes sluggish cellular organs.
* **Bonus:** When you register with the ₦10,000 Foretaste package, you receive **1 full bottle of Detox Plus** free!`,
      actionButton: {
        label: 'View Detox Plus Details',
        path: '/products/detox-plus'
      },
      relatedSuggestions: [
        'How do I register with ₦10,000?',
        'Explain the 14% binary pairing bonus',
        'What are the 12 products?'
      ]
    };
  }

  // 8. D-Man / Men's Health / Prostate / Libido Queries
  if (
    q.includes('d-man') ||
    q.includes('dman') ||
    q.includes('prostate') ||
    q.includes('erect') ||
    q.includes('libido') ||
    q.includes('stamina') ||
    q.includes('men') ||
    q.includes('male') ||
    q.includes('sex') ||
    q.includes('bph')
  ) {
    return {
      text: `### ⚡ D-Man: Advanced Male Vitality & Prostate Care

**D-Man** is Milnapath’s potent botanical restorative for men:

* **Retail Price:** ₦16,000 | **Wholesale Price:** ₦12,500 (16 PV)
* **Prostate Protection:** Naturally shrinks benign prostatic enlargement (BPH), halts painful nocturnal urination, and restores a steady urinary stream.
* **Stamina & Libido:** Elevates natural testosterone, reverses erectile weakness, improves bedroom stamina, and supports healthy sperm count.`,
      actionButton: {
        label: 'View D-Man Details',
        path: '/products/d-man'
      },
      relatedSuggestions: [
        'What are all 12 products?',
        'Explain the 14% binary pairing bonus',
        'How do I register with ₦10,000?'
      ]
    };
  }

  // 9. Glucomil / Diabetes / Blood Sugar Queries
  if (
    q.includes('glucomil') ||
    q.includes('diabet') ||
    q.includes('sugar') ||
    q.includes('glucose') ||
    q.includes('insulin') ||
    q.includes('pancreas')
  ) {
    return {
      text: `### 🩸 Glucomil: Herbal Blood Sugar Regulation

**Glucomil** is formulated for individuals struggling with type 2 diabetes and fluctuating blood sugar levels:

* **Retail Price:** ₦14,000 | **Wholesale Price:** ₦11,200 (14 PV)
* **Benefits:** Revitalizes damaged pancreatic beta cells, boosts natural insulin sensitivity, reduces sugar cravings, and prevents diabetic complications like vision blurriness and slow-healing sores.`,
      actionButton: {
        label: 'View Glucomil Details',
        path: '/products/glucomil'
      },
      relatedSuggestions: [
        'Tell me about Control Oil',
        'What are all 12 products?',
        'How to order products'
      ]
    };
  }

  // 10. Control Oil / Blood Pressure / Hypertension Queries
  if (
    q.includes('control oil') ||
    q.includes('blood pressure') ||
    q.includes('hypertension') ||
    q.includes('cholesterol') ||
    q.includes('cardio') ||
    q.includes('heart')
  ) {
    return {
      text: `### ❤️ Control Oil: Cardiovascular & Blood Pressure Balance

**Control Oil** is an essential cardiovascular botanical formulation:

* **Retail Price:** ₦12,500 | **Wholesale Price:** ₦9,800 (12 PV)
* **Benefits:** Dilates constricted blood vessels, dissolves bad arterial LDL cholesterol plaques, maintains healthy systolic/diastolic blood pressure, and lowers the risk of cardiac arrest and stroke.`,
      actionButton: {
        label: 'View Control Oil Details',
        path: '/products/control-oil'
      },
      relatedSuggestions: [
        'Tell me about Rejuvenating Drink',
        'What are all 12 products?',
        'How to register'
      ]
    };
  }

  // 11. Point Flushing Queries (Do points flush?)
  if (
    q.includes('flush') ||
    q.includes('expire') ||
    q.includes('wipe') ||
    q.includes('month end') ||
    q.includes('carry over')
  ) {
    return {
      text: `### 🛡️ Do Points Flush in Milnapath? (Strict Non-Flush Policy)

**NO. Milnapath has a strict 100% NON-FLUSH policy.**

* In Milnapath, **your points NEVER expire or reset to zero** at the end of the month.
* In the **14% Binary Plan**, if you have more volume on one leg, the excess unmatched PV safely **carries forward indefinitely** until balanced by new volume.
* In the **Cumulative Rank Awards**, every single point accumulated on your lesser leg continues adding up until you reach the **Laptop (1,500 PV)**, **₦5M Car (25,000 PV)**, **₦15M Car (75,000 PV)**, and **₦60M Luxury Villa (300,000 PV)**!
* You never lose points due to calendar changes or inactivity.`,
      actionButton: {
        label: 'Check Rank Awards Progression',
        path: '/compensation'
      },
      relatedSuggestions: [
        'Explain the 14% binary pairing bonus',
        'What are the 12 Ways to Earn?',
        'How do I register with ₦10,000?'
      ]
    };
  }

  // 12. Package Tiers and Daily Caps
  if (
    q.includes('package') ||
    q.includes('tier') ||
    q.includes('caps') ||
    q.includes('daily cap') ||
    q.includes('vip tier') ||
    q.includes('elite tier') ||
    q.includes('standard tier') ||
    q.includes('entry tier') ||
    q.includes('upgrade')
  ) {
    return {
      text: `### 📦 Milnapath Package Tiers & Daily Binary Caps

Choose an entry package that matches your financial goals:

* **Foretaste (Starter):** ₦10,000 (10 PV) | 20% Direct Bonus (₦2,000) | 3-Level Foretaste Matrix.
* **Entry Tier:** ₦30,000 (40 PV) | 20% Direct Bonus | **Cap: 25 pairs/day (₦70,000/day)**
* **Standard Tier:** ₦60,000 (80 PV) | 22% Direct Bonus | **Cap: 40 pairs/day (₦112,000/day)**
* **Executive Tier:** ₦180,000 (240 PV) | 24% Direct Bonus | **Cap: 60 pairs/day (₦168,000/day)**
* **Elite Tier:** ₦420,000 (560 PV) | 26% Direct Bonus | **Cap: 100 pairs/day (₦280,000/day)**
* **VIP Tier (Maximum):** ₦840,000 (1,125 PV) | 28% Direct Bonus | **Cap: 175 pairs/day (₦490,000/day = ₦14.7M/mo)**

*Upgrades:* You can start with **₦10,000 Foretaste** today and upgrade anytime simply by paying the cost difference!`,
      actionButton: {
        label: 'View All Package Deliverables',
        path: '/compensation'
      },
      relatedSuggestions: [
        'Explain the 14% binary pairing bonus',
        'How do I register with ₦10,000?',
        'Do points flush?'
      ]
    };
  }

  // 13. Stockist Queries
  if (
    q.includes('stockist') ||
    q.includes('distribution hub') ||
    q.includes('franchise') ||
    q.includes('agency')
  ) {
    return {
      text: `### 🏢 Milnapath Stockist Hub Opportunities & Earnings

Becoming an authorized Milnapath Regional Stockist allows you to earn substantial commercial overrides on all products moving through your center:

* **Mini Stockist:** Minimum stock purchase of **₦2,000,000** | Earns **4.5%** cash operational override on all product distributions.
* **Super Stockist:** Minimum stock purchase of **₦5,000,000** | Earns **6.0%** cash operational override on all product distributions.
* **Mega Stockist:** Minimum stock purchase of **₦10,000,000** | Earns **7.5%** cash operational override on all product distributions.

*Stockist Advantage:* You earn on ALL distributors picking up products at your hub, regardless of whether they are in your personal team or from other cross-line organizations!`,
      actionButton: {
        label: 'Apply for Stockist Mentorship',
        path: '/apply'
      },
      relatedSuggestions: [
        'How do I register with ₦10,000?',
        'What are the 12 Ways to Earn?',
        'Explain the 14% binary pairing bonus'
      ]
    };
  }

  // 14. All 12 Products Overview
  if (
    q.includes('all product') ||
    q.includes('list of product') ||
    q.includes('products') ||
    q.includes('catalogue') ||
    q.includes('catalog')
  ) {
    return {
      text: `### 🌿 The Complete Milnapath 12-Product Herbal Line

All 12 Milnapath formulas are **NAFDAC Approved**, organic, and clinically formulated:

1. **Detox Plus:** Colon, liver & full-body detoxification (₦9,500 retail / ₦7,500 wholesale, 10 PV).
2. **Gastro-Pro:** Severe peptic ulcers, acid reflux, H. pylori (₦12,000 / ₦9,500, 12 PV).
3. **Nakom Oil:** Fast-acting rub for arthritis, joint pain & stroke recovery (₦11,500 / ₦9,000, 12 PV).
4. **Gynomil:** Fibroids, ovarian cysts, hormonal imbalance & fertility (₦14,000 / ₦11,000, 15 PV).
5. **Peptic Tea:** Soothing digestive lining repair & ulcer tea (₦8,500 / ₦6,500, 8 PV).
6. **Body Lotion & Soap:** Radiant skincare, anti-aging, blemish removal (₦10,500 / ₦8,000, 10 PV).
7. **Control Oil:** Hypertension, cholesterol & cardiovascular health (₦12,500 / ₦9,800, 12 PV).
8. **Rejuvenating Drink:** Anti-aging, cellular vitality & longevity (₦17,500 / ₦14,000, 18 PV).
9. **Glucomil:** Blood sugar regulation & pancreatic support (₦14,000 / ₦11,200, 14 PV).
10. **D-Man:** Prostate enlargement, male stamina & virility (₦16,000 / ₦12,500, 16 PV).
11. **Blood Building Tea:** Anemia, low PCV & immune defense (₦9,500 / ₦7,500, 9 PV).
12. **Malaria & Typhoid Shield:** Resistant malaria & chronic typhoid (₦11,000 / ₦8,500, 11 PV).`,
      actionButton: {
        label: 'Explore Full Visual Product Catalog',
        path: '/products'
      },
      relatedSuggestions: [
        'Which product is best for ulcer & acid reflux?',
        'Tell me about Gynomil for fibroids',
        'How do I register with ₦10,000?'
      ]
    };
  }

  // 15. Mentorship, Funnel, Team Benefits
  if (
    q.includes('mentorship') ||
    q.includes('masterclass') ||
    q.includes('funnel') ||
    q.includes('training') ||
    q.includes('vsl') ||
    q.includes('spillover')
  ) {
    return {
      text: `### 🚀 Milnapath VIP Direct Mentorship & Sales Funnel

When you register through our official team gateway, you don't just get products—you get a comprehensive digital marketing engine:

* **Free Turnkey Sales Funnel:** Ready-made high-converting landing pages and video presentations to recruit on autopilot.
* **Weekly Live Zoom Masterminds:** Direct training from top 7-figure network marketing earners and wellness experts.
* **Automated Spillover Placements:** Our top team builders actively place new incoming members on your binary power leg, accelerating your 14% matching pairs!
* **Zero Solo Guesswork:** Step-by-step advertising blueprints for Facebook, TikTok, and WhatsApp marketing.`,
      actionButton: {
        label: 'Watch Video Masterclass',
        path: '/vsl'
      },
      relatedSuggestions: [
        'How do I register with ₦10,000?',
        'Explain the 14% binary pairing bonus',
        'What are the 12 Ways to Earn?'
      ]
    };
  }

  // 16. General Fallback with Smart Guidance
  return {
    text: `### 🤖 Milnapath VIP Support Assistant

I am trained on the complete Milnapath International platform, including all 12 products, the full compensation plan, registration details, and clinical guidelines.

Regarding **"${query}"**:
* **Official GT Bank:** 0718549018 (*Millennium Nature's Path Intl*)
* **Registration:** Starts at **₦10,000** for the Foretaste Tier (includes 1 free bottle of Detox Plus).
* **Exchange Rate:** 1 PV = $1 = **₦500**.
* **Binary Pairing:** Earn **14%** on matched volume to infinite depth (₦2,800 per 40 PV pair).
* **Non-Flush Guarantee:** Points NEVER expire or wipe out at month-end!

Would you like me to explain any of the topics below in detail?`,
    actionButton: {
      label: 'Register Account (₦10,000)',
      path: '/register'
    },
    relatedSuggestions: [
      'Explain the 14% binary pairing bonus',
      'How do I register with ₦10,000 (GT Bank)?',
      'What are the 12 Ways to Earn in Milnapath?',
      'Which product is best for ulcer & acid reflux?'
    ]
  };
}
